{{- if .Values.logging.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "{{- .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: vdl
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: "alloy"
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.3.0
    helm.sh/chart: {{- .Chart.name }}
  name: "vdl-alloy-{{- .Values.core.nodeNr }}"
  namespace: "{{- .Release.Namespace }}"
{{- end}}
