{{- if .Values.logging.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.name }}
    meta.helm.sh/release-namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.3.0
    helm.sh/chart: {{- .Chart.name }}
  name: "vdl{{- .Values.core.nodeNr }}-alloy"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "vdl{{- .Values.core.nodeNr }}-alloy"
subjects:
- kind: ServiceAccount
  name: vdl-alloy-{{- .Values.core.nodeNr }}
  namespace: "{{- .Release.Namespace }}"
{{- end }}
