{{- if .Values.sendLogs -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-filebeat-config
data:
  filebeat.yml: |
    filebeat:
      inputs:
        - type: filestream
          id: {{ .Chart.Name }}-node-logs
          paths:
            - /var/log/vdl/*.log
    # cloud.id: {{ required ".Values.elasticCloudID is required when .Values.sendLogs is true" .Values.elasticCloudID | quote }}
    # cloud.auth: {{ required ".Values.elasticCloudAuth is required when .Values.sendLogs is true" .Values.elasticCloudAuth | quote }}
    # output.elasticsearch.index: "{{ required ".Values.elasticIndex is required when .Values.sendLogs is true" .Values.elasticIndex }}-%{[agent.version]}"
    # output.elasticsearch.allow_older_versions: true
    output.logstash:
      hosts: ["{{ .Values.logstashHost}}"]
    setup.template.name: "{{ .Values.elasticIndex }}"
    setup.template.pattern: "{{ .Values.elasticIndex }}-%{[agent.version]}"
{{- end }}
