{{- if .Values.sendLogs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-filebeat-tls-secrets
data:
  filebeat-client.key: |-
    {{ required ".Values.filebeatKey is missing while sendLogs is true" .Values.filebeatKey }}
  filebeat-client.crt: |-
    {{ required ".Values.filebeatCrt is missing while sendLogs is true" .Values.filebeatCrt }}
  logging-ca.crt: |-
    {{ required ".Values.loggingCaCrt is missing while sendLogs is true" .Values.loggingCaCrt }}
{{- end }}
