{{- if .Values.logging.isHost -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-vpn-config
data:
  client.ovpn: |-
    {{ required "Add flag: --set-file grafanaVpnConfigFile=<(base64 -w0 < /path/to/client.ovpn) to helm install" .Values.grafanaVpnConfigFile }}
{{- end }}
