apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret-vdl
data:
  selfsignedca.crt: |-
    {{ .Values.secrets.selfsignedcaCrt }}
  license.key: |-
    {{ .Values.secrets.licenseKey }}

  httpd0.crt: |-
    {{ .Values.secrets.httpd0Crt }}
  httpd0.key: |-
    {{ .Values.secrets.httpd0Key }}
  httpd1.crt: |-
    {{ .Values.secrets.httpd1Crt }}
  httpd1.key: |-
    {{ .Values.secrets.httpd1Key }}
  httpd2.crt: |-
    {{ .Values.secrets.httpd2Crt }}
  httpd2.key: |-
    {{ .Values.secrets.httpd2Key }}

  server0.crt: |-
    {{ .Values.secrets.server0Crt }}
  server0.key: |-
    {{ .Values.secrets.server0Key }}
  server0.pk: |-
    {{ .Values.secrets.server0Pk }}
  server0.sk.b64: |-
    {{ .Values.secrets.server0SkB64 }}

  server1.crt: |-
    {{ .Values.secrets.server1Crt }}
  server1.key: |-
    {{ .Values.secrets.server1Key }}
  server1.pk: |-
    {{ .Values.secrets.server1Pk }}
  server1.sk.b64: |-
    {{ .Values.secrets.server1SkB64 }}

  server2.crt: |-
    {{ .Values.secrets.server2Crt }}
  server2.key: |-
    {{ .Values.secrets.server2Key }}
  server2.pk: |-
    {{ .Values.secrets.server2Pk }}
  server2.sk.b64: |-
    {{ .Values.secrets.server2SkB64 }}

  sign0.pk: |-
    {{ .Values.secrets.sign0Pk }}
  sign1.pk: |-
    {{ .Values.secrets.sign1Pk }}
  sign2.pk: |-
    {{ .Values.secrets.sign2Pk }}
  sign0.pk.b64: |-
    {{ .Values.secrets.sign0PkB64 }}
  sign1.pk.b64: |-
    {{ .Values.secrets.sign1PkB64 }}
  sign2.pk.b64: |-
    {{ .Values.secrets.sign2PkB64 }}
